# [START app_yaml]
runtime: nodejs
env: flex
service: public-apis

skip_files:
- .git
- node_modules

manual_scaling:
  instances: 1

# [START cloudsql_settings]
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: utopia-315014:us-west1:utp-dex-db
# [END cloudsql_settings]
# [END app_yaml]